apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-netutils
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-net-1
spec:
  containers:
  - name:  ubuntu-netutils
    image: 291615555612.dkr.ecr.us-east-1.amazonaws.com/sigitp-ecr:ubuntu-netutils
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        cpu: 1
        memory: 0.5Gi
        hugepages-1Gi: 2Gi
        intel.com/sriov_netdevice_1: '1'
        intel.com/sriov_netdevice_2: '1'
      limits:
        cpu: 1
        memory: 0.5Gi
        hugepages-1Gi: 2Gi
        intel.com/sriov_netdevice_1: '1'
        intel.com/sriov_netdevice_2: '1'
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: longhorn-pvc
